Уважаемые студенты!

Задачи выполняются с помощью стандартных библиотек питона без установки сторонних библиотек. Все задачи направлены на проверку усвоения пройденного материала. Вспомните как работать с библиотекой numpy.

Желаем удачи!

**Задача №1**. **Написать формулу которая находит ближайшее значение к переменной x из значений в массиве X:**

- Подсказка 1: np.abs, argmin, flat
- Подсказка 2: Для значений:
> X = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])
>
> x = 0.5
> Правильный ответ будет: 0.48059102


In [ ]:
import numpy as np

def nearest(X, a):
  differences = np.abs(X - x)
  min_i = np.argmin(differences)
  return X[min_i]


X = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])
x = float(input("Введите число: "))
print(nearest(X, x))

Введите число: 0.5
0.48059102


**Задача №2**. **Какой из следующих массивов является двумерным (2D) массивом?**

1. 56
2. [[4,6,7], [8,6,8]]
3. [4, 6, 7]



In [ ]:
# ответ [[4,6,7], [8,6,8]]

**Задача №3**. **Как правильно сделать print числа 7 из массива:**

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

    1. print(arr[7,2])
    2. print(arr[2,0])
    3. print(arr[1,1])


In [ ]:
# ответ print(arr[1,1])

7


**Задача №4**. **Как правильно сделать массив [3, 4, 5, 6] из массива:**

arr = np.array([1,2,3,4,5,6,7,8,9])

    1. print(arr[2:6])
    2. print(arr[2:5])
    3. print(arr[3:6])
    4. print(arr[1:6])

In [ ]:
# ответ print(arr[2:6])

[3 4 5 6]


**Задача №5**. **Какое выражение выведет каждый второй элемент из массива:**

arr = np.array([1,2,3,4,5,6,7])

    1. print(arr[1:3:5:7])
    2. print(arr[::2])
    3. print(arr(0: step=2))

In [ ]:
# ответ print(arr[::2])

[1 3 5 7]


**Задача №6**. **Как правильно сделать массив индексов всех элементов, имеющих значение 4 из массива ниже:**

arr = np.array([1,4,3,4,5,4,4])

    1. arr.where(4)
    2. np.where(arr==4)
    3. arr.search(4)

In [ ]:
# ответ np.where(arr==4)

(array([1, 3, 5, 6]),)

**Задача №7**. **Написать формулу которая создает матрицу (двумерный массив) 3x3 со значениями от 0 до 8**

In [ ]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Задача №8**. **Используя формулы numpy создать матрицу m с 1 внутри и 0 на границах**

Подсказка 1: np.zeros

Подсказка 2: матрица будет такая:

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np

arr = np.zeros((5,5))
arr[1:4, 1:4] = 1
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**Задача №9**. **Создайте вектор размером 10 со значениями в диапазоне от 0 до 1, 0 и 1 не должны быт в этом векторе.**

Подсказка: np.linspace

In [ ]:
import numpy as np

arr = np.linspace(0, 1, 12)[1:-1]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**Задача №10**. **Что выведет код:**

a = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)

1. 1
2. (1,3)
3. 3
4. (3,1)

In [ ]:
# ответ 3

3

**Задача №11**. **Что из перечисленного является правильным способом транспонирования матрицы A?**

    1. Trans(A)
    2. Transpose(A)
    3. A.T
    4. A.Transpose


In [ ]:
# ответ A.T

**Задача №12**. **Что выведет print в коде:**

a = np.array([1,2,3,4,5])

b = np.arange(0,10,2)

c = a + b

print (c[4])


In [ ]:
# ответ 13

13
